//
//  AppListModule.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation
import UIKit

class AppListModule: AppListBuilderProtocol {

    static func build() -> UIViewController {
        let view = AppListViewController(nibName: "AppListViewController", bundle: Bundle(for: AppListViewController.self))
        let presenter = AppListPresenter(view: view)
        
        view.presenter = presenter
        
        return view
    }
}
