// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef ICCHATSDKV2_SWIFT_H
#define ICCHATSDKV2_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AsyncDisplayKit;
@import CoreGraphics;
@import Foundation;
@import ICheckBaseUI;
@import ICheckCore;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ICChatSDKV2",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class ASLayoutSpec;

SWIFT_CLASS("_TtC11ICChatSDKV223ICActivityIndicatorNode")
@interface ICActivityIndicatorNode : ICUDisplayNode
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICBlockedNode")
@interface ICBlockedNode : ICUDisplayNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC11ICChatSDKV213ICChatBlocker")
@interface ICChatBlocker : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable fromId;
@property (nonatomic, copy) NSString * _Nullable toId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV218ICChatColorsConfig")
@interface ICChatColorsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICContentMessage;

SWIFT_CLASS("_TtC11ICChatSDKV212ICChatDetail")
@interface ICChatDetail : ICBaseModel
@property (nonatomic, strong) ICContentMessage * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable senderId;
@property (nonatomic, copy) NSString * _Nullable messageId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV215ICChatEmptyNode")
@interface ICChatEmptyNode : ICUDisplayNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class ASMultiplexImageNode;
@class NSURL;
@class UIImage;

SWIFT_CLASS("_TtC11ICChatSDKV219ICChatLazyImageNode")
@interface ICChatLazyImageNode : ICUCellNode <ASMultiplexImageNodeDataSource, ASMultiplexImageNodeDelegate>
@property (nonatomic) UIViewContentMode contentMode;
@property (nonatomic) CGFloat cornerRadius;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSURL * _Nullable)multiplexImageNode:(ASMultiplexImageNode * _Nonnull)imageNode URLForImageIdentifier:(ASImageIdentifier _Nonnull)imageIdentifier SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)multiplexImageNode:(ASMultiplexImageNode * _Nonnull)imageNode imageForImageIdentifier:(ASImageIdentifier _Nonnull)imageIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)multiplexImageNode:(ASMultiplexImageNode * _Nonnull)imageNode didFinishDownloadingImageWithIdentifier:(ASImageIdentifier _Nonnull)imageIdentifier error:(NSError * _Nullable)error;
@end


@interface ICChatLazyImageNode (SWIFT_EXTENSION(ICChatSDKV2))
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC11ICChatSDKV213ICChatManager")
@interface ICChatManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICChatProduct;

SWIFT_PROTOCOL("_TtP11ICChatSDKV221ICChatManagerDelegate_")
@protocol ICChatManagerDelegate
@optional
- (void)unReadCountOfAllWithCount:(NSInteger)count;
- (void)scanditWithScanBarCodeSuccess:(void (^ _Nonnull)(ICChatProduct * _Nonnull))scanBarCodeSuccess scanQRCodeSuccess:(void (^ _Nonnull)(NSString * _Nonnull))scanQRCodeSuccess;
- (void)showPageDetailWithId:(NSInteger)id;
- (void)showMemberProfileWithId:(NSInteger)id;
- (void)productDetailWithBarcode:(NSString * _Nonnull)barcode;
- (void)shopDetailWithIdShop:(NSInteger)idShop;
- (void)campaignDetailWithIdCampaign:(NSString * _Nonnull)idCampaign;
- (void)clickLinkWithUrl:(NSURL * _Nonnull)url;
- (void)block;
- (void)unblock;
- (void)downloadMediaWithStatus:(NSInteger)status;
- (void)isLoadingWithLoading:(BOOL)loading;
- (void)showErrorWithError:(NSString * _Nonnull)error;
- (void)showAlertSuccessWithMessage:(NSString * _Nonnull)message;
@end

@class PHAsset;

SWIFT_CLASS("_TtC11ICChatSDKV211ICChatMedia")
@interface ICChatMedia : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable messageId;
@property (nonatomic, strong) PHAsset * _Nullable asset;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIEvent;

SWIFT_CLASS("_TtC11ICChatSDKV220ICChatNavigationNode")
@interface ICChatNavigationNode : ASDisplayNode
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)didLoad;
- (void)layoutDidFinish;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC11ICChatSDKV216ICChatPlayerView")
@interface ICChatPlayerView : UIView
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICChatProduct")
@interface ICChatProduct : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable state;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICChatResponseValidation;

SWIFT_CLASS("_TtC11ICChatSDKV214ICChatResponse")
@interface ICChatResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable statusCode;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable messages;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic) id _Nullable unknownData;
@property (nonatomic, copy) NSArray<ICChatResponseValidation *> * _Nullable validationErrors;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@property (nonatomic, readonly, copy) NSString * _Nullable messageWithError;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV224ICChatResponseValidation")
@interface ICChatResponseValidation : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable property;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable constraints;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV216ICChatSearchNode")
@interface ICChatSearchNode : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV212ICChatSender")
@interface ICChatSender : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable senderId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV216ICChatSenderCell")
@interface ICChatSenderCell : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICChatSticker")
@interface ICChatSticker : ICChatMedia
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ASTextKitComponents;

SWIFT_CLASS("_TtC11ICChatSDKV218ICChatTextViewNode")
@interface ICChatTextViewNode : ASEditableTextNode
- (void)layoutDidFinish;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextKitComponents:(ASTextKitComponents * _Nonnull)textKitComponents placeholderTextKitComponents:(ASTextKitComponents * _Nonnull)placeholderTextKitComponents OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV221ICChatTitleHeaderNode")
@interface ICChatTitleHeaderNode : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV214ICChatUploader")
@interface ICChatUploader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV215ICChatVideoNode")
@interface ICChatVideoNode : ICUCellNode
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11ICChatSDKV216ICContentMessage")
@interface ICContentMessage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) ICChatProduct * _Nullable product;
@property (nonatomic, copy) NSArray<ICChatMedia *> * _Nullable media;
@property (nonatomic, copy) NSString * _Nullable link;
@property (nonatomic, strong) ICChatSticker * _Nullable sticker;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICConversationActivity;

SWIFT_CLASS("_TtC11ICChatSDKV214ICConversation")
@interface ICConversation : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable roomId;
@property (nonatomic) BOOL enableAlert;
@property (nonatomic) NSInteger unreadCount;
@property (nonatomic, strong) ICConversationActivity * _Nullable lastActivity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV222ICConversationActivity")
@interface ICConversationActivity : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV222ICConversationCellNode")
@interface ICConversationCellNode : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV219ICDetailStickerNode")
@interface ICDetailStickerNode : ICUCellNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ASCollectionNode;
@class NSIndexPath;
@class ASCellNode;

@interface ICDetailStickerNode (SWIFT_EXTENSION(ICChatSDKV2)) <ASCollectionDataSource, ASCollectionDelegateFlowLayout>
- (NSInteger)collectionNode:(ASCollectionNode * _Nonnull)collectionNode numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (ASCellNode * _Nonnull)collectionNode:(ASCollectionNode * _Nonnull)collectionNode nodeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (ASSizeRange)collectionNode:(ASCollectionNode * _Nonnull)collectionNode constrainedSizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionNode:(ASCollectionNode * _Nonnull)collectionNode didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11ICChatSDKV219ICFirebaseChatUtils")
@interface ICFirebaseChatUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC11ICChatSDKV217ICLinkPreviewNode")
@interface ICLinkPreviewNode : ICUDisplayNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV211ICMediaCell")
@interface ICMediaCell : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV211ICMediaNode")
@interface ICMediaNode : ICUDisplayNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ICMediaNode (SWIFT_EXTENSION(ICChatSDKV2)) <ASCollectionDataSource, ASCollectionDelegateFlowLayout>
- (NSInteger)collectionNode:(ASCollectionNode * _Nonnull)collectionNode numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (ASCellNode * _Nonnull)collectionNode:(ASCollectionNode * _Nonnull)collectionNode nodeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (ASSizeRange)collectionNode:(ASCollectionNode * _Nonnull)collectionNode constrainedSizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11ICChatSDKV212ICMemberChat")
@interface ICMemberChat : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICMessageCell")
@interface ICMessageCell : ICUCellNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

@interface ICMessageCell (SWIFT_EXTENSION(ICChatSDKV2)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
@end


@class UIColor;

SWIFT_CLASS("_TtC11ICChatSDKV218ICOptionSetingNode")
@interface ICOptionSetingNode : ICUDisplayNode
@property (nonatomic, copy) NSString * _Nullable titleString;
@property (nonatomic, strong) UIColor * _Nullable titleColor;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV218ICPreViewMediaCell")
@interface ICPreViewMediaCell : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV218ICPreviewMediaNode")
@interface ICPreviewMediaNode : ICUDisplayNode
- (void)didLoad;
- (void)layoutDidFinish;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ICPreviewMediaNode (SWIFT_EXTENSION(ICChatSDKV2)) <ASCollectionDataSource, ASCollectionDelegateFlowLayout>
- (NSInteger)collectionNode:(ASCollectionNode * _Nonnull)collectionNode numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (ASCellNode * _Nonnull)collectionNode:(ASCollectionNode * _Nonnull)collectionNode nodeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (ASSizeRange)collectionNode:(ASCollectionNode * _Nonnull)collectionNode constrainedSizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICProductNode")
@interface ICProductNode : ICUDisplayNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV220ICProductPreviewNode")
@interface ICProductPreviewNode : ICUDisplayNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV210ICRoomChat")
@interface ICRoomChat : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable roomName;
@property (nonatomic, copy) NSString * _Nullable roomId;
@property (nonatomic, copy) NSArray<ICMemberChat *> * _Nullable members;
@property (nonatomic, strong) ICChatBlocker * _Nullable blocker;
@property (nonatomic, copy) NSString * _Nullable createAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICStickerCell")
@interface ICStickerCell : ICUCellNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ICChatSDKV214ICStickersNode")
@interface ICStickersNode : ICUCellNode
- (void)didLoad;
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

@interface ICStickersNode (SWIFT_EXTENSION(ICChatSDKV2)) <ASCollectionDataSource, ASCollectionDelegateFlowLayout>
- (NSInteger)collectionNode:(ASCollectionNode * _Nonnull)collectionNode numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (ASCellNode * _Nonnull)collectionNode:(ASCollectionNode * _Nonnull)collectionNode nodeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (ASSizeRange)collectionNode:(ASCollectionNode * _Nonnull)collectionNode constrainedSizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionNode:(ASCollectionNode * _Nonnull)collectionNode didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end


SWIFT_CLASS("_TtC11ICChatSDKV213ICUnBlockNode")
@interface ICUnBlockNode : ICUDisplayNode
- (ASLayoutSpec * _Nonnull)layoutSpecThatFits:(ASSizeRange)constrainedSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC11ICChatSDKV224ISChatBaseViewController")
@interface ISChatBaseViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
