// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef ICHECKVIETTELSDK_SWIFT_H
#define ICHECKVIETTELSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ICheckCore;
@import ICheckNetworking;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ICheckViettelSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC16ICheckViettelSDK13ICCustomField")
@interface ICCustomField : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable stringValues;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nullable dateString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK12ICVBaseModel")
@interface ICVBaseModel : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVNoteGuarantee;

SWIFT_CLASS("_TtC16ICheckViettelSDK19ICListNoteGuarantee")
@interface ICListNoteGuarantee : ICVBaseModel
@property (nonatomic, copy) NSArray<ICVNoteGuarantee *> * _Nonnull items;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK9ICVActive")
@interface ICVActive : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable activeTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK13ICVAttachment")
@interface ICVAttachment : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC16ICheckViettelSDK11ICVBusiness")
@interface ICVBusiness : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable attachments;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable username;
@property (nonatomic, copy) NSString * _Nullable website;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSString * _Nullable wardName;
@property (nonatomic, copy) NSString * _Nullable countryName;
@property (nonatomic, readonly, copy) NSString * _Nullable detailAddress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK7ICVCity")
@interface ICVCity : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable nameFolding;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVContact;

SWIFT_CLASS("_TtC16ICheckViettelSDK9ICVConfig")
@interface ICVConfig : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSArray<ICVContact *> * _Nullable contacts;
@property (nonatomic, copy) NSString * _Nullable msgError;
@property (nonatomic, copy) NSString * _Nullable msgSmsError;
@property (nonatomic, copy) NSString * _Nullable msgSmsSuccess;
@property (nonatomic, copy) NSString * _Nullable msgSmsWarning;
@property (nonatomic, copy) NSString * _Nullable msgSuccess;
@property (nonatomic, copy) NSString * _Nullable msgWarning;
@property (nonatomic, copy) NSString * _Nullable termGuaranteeContent;
@property (nonatomic, copy) NSString * _Nullable termGuaranteeIntro;
@property (nonatomic, copy) NSString * _Nullable termGuaranteeTitle;
@property (nonatomic, copy) NSString * _Nullable termVerifyContent;
@property (nonatomic, copy) NSString * _Nullable termVerifyIntro;
@property (nonatomic, copy) NSString * _Nullable termVerifyTitle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK10ICVContact")
@interface ICVContact : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable hotline;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC16ICheckViettelSDK8ICVCount")
@interface ICVCount : ICVBaseModel
@property (nonatomic) NSInteger peopleCount;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable prefix;
@property (nonatomic) NSInteger scanCount;
@property (nonatomic, copy) NSString * _Nullable icheckId;
- (NSString * _Nullable)serialString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK17ICVCurrentScanner")
@interface ICVCurrentScanner : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable activeTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVCustomerField;

SWIFT_CLASS("_TtC16ICheckViettelSDK11ICVCustomer")
@interface ICVCustomer : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable icheckId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable storeId;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable fields;
@property (nonatomic, copy) NSArray<ICVCustomerField *> * _Nonnull dynamicFields;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK16ICVCustomerField")
@interface ICVCustomerField : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable stringValues;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSString * _Nullable dateString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK11ICVDistrict")
@interface ICVDistrict : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable nameFolding;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVDynamicFieldOption;

SWIFT_CLASS("_TtC16ICheckViettelSDK15ICVDynamicField")
@interface ICVDynamicField : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSArray<ICVDynamicFieldOption *> * _Nullable options;
@property (nonatomic) id _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK21ICVDynamicFieldOption")
@interface ICVDynamicFieldOption : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK12ICVEcommerce")
@interface ICVEcommerce : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable images;
@property (nonatomic, copy) NSString * _Nullable link;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK8ICVError")
@interface ICVError : ICBaseModel
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK8ICVField")
@interface ICVField : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVLastGuarantee;
@class ICVTime;

SWIFT_CLASS("_TtC16ICheckViettelSDK12ICVGuarantee")
@interface ICVGuarantee : ICVBaseModel
@property (nonatomic, strong) ICVLastGuarantee * _Nullable lastGuarantee;
@property (nonatomic, strong) ICVTime * _Nullable time;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK17ICVGuaranteeField")
@interface ICVGuaranteeField : ICBaseModel
@property (nonatomic, strong) ICVField * _Nullable nhanvientiepnhan;
@property (nonatomic, strong) ICVField * _Nullable lidobaohanh;
@property (nonatomic, strong) ICVField * _Nullable ngayhentrabaohanh;
@property (nonatomic, strong) ICVField * _Nullable mucđouutien;
@property (nonatomic, strong) ICVField * _Nullable ngaytrabh;
@property (nonatomic, strong) ICVField * _Nullable nhanvien;
@property (nonatomic, strong) ICVField * _Nullable note;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVGuaranteeStatus;
@class ICVStore;
@class ICVGuaranteeState;

SWIFT_CLASS("_TtC16ICheckViettelSDK16ICVLastGuarantee")
@interface ICVLastGuarantee : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable expiredTime;
@property (nonatomic, copy) NSString * _Nullable prefix;
@property (nonatomic, strong) ICVGuaranteeStatus * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable returnTime;
@property (nonatomic, strong) ICVStore * _Nullable store;
@property (nonatomic, strong) ICVCustomer * _Nullable customer;
@property (nonatomic, strong) ICVGuaranteeState * _Nullable state;
@property (nonatomic, copy) NSArray<ICCustomField *> * _Nonnull fields;
@property (nonatomic, copy) NSString * _Nullable productCode;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull images;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK15ICVGuaranteeLog")
@interface ICVGuaranteeLog : ICVLastGuarantee
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK17ICVGuaranteeState")
@interface ICVGuaranteeState : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable instDt;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK18ICVGuaranteeStatus")
@interface ICVGuaranteeStatus : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable instDt;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK19ICVHistoryGuarantee")
@interface ICVHistoryGuarantee : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable storeName;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable createTime;
@property (nonatomic, copy) NSString * _Nullable returnTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK7ICVInfo")
@interface ICVInfo : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable shortContent;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable image;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK11ICVInstance")
@interface ICVInstance : ICBaseInstance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ICVInstance * _Nonnull shared;)
+ (ICVInstance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)signInWithToken:(NSString * _Nonnull)token handler:(void (^ _Nullable)(BOOL))handler;
- (nonnull instancetype)icheckId:(NSString * _Nullable (^ _Nullable)(void))icheckId;
- (nonnull instancetype)deviceId:(NSString * _Nullable (^ _Nullable)(void))deviceId;
- (nonnull instancetype)latitude:(NSString * _Nullable (^ _Nullable)(void))latitude;
- (nonnull instancetype)longtitude:(NSString * _Nullable (^ _Nullable)(void))longtitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVInternalCodeSuggest;

SWIFT_CLASS("_TtC16ICheckViettelSDK23ICVInternalCodeResponse")
@interface ICVInternalCodeResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSArray<ICVInternalCodeSuggest *> * _Nonnull suggest_app;
@property (nonatomic, copy) NSString * _Nullable urlIdentity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK22ICVInternalCodeSuggest")
@interface ICVInternalCodeSuggest : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable target;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC16ICheckViettelSDK16ICVNoteGuarantee")
@interface ICVNoteGuarantee : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull images;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable logId;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVVendor;

SWIFT_CLASS("_TtC16ICheckViettelSDK10ICVProduct")
@interface ICVProduct : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable images;
@property (nonatomic, copy) NSArray<ICVInfo *> * _Nullable infos;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable updatedTime;
@property (nonatomic, copy) NSString * _Nullable userCreated;
@property (nonatomic, strong) ICVVendor * _Nullable vendor;
@property (nonatomic, copy) NSString * _Nullable video;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK17ICVProductVariant")
@interface ICVProductVariant : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable extra;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK11ICVResponse")
@interface ICVResponse : ICBaseModel
@property (nonatomic) id _Nullable data;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK14ICVScanMessage")
@interface ICVScanMessage : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable text;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK13ICVScanObject")
@interface ICVScanObject : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable icheckId;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable lat;
@property (nonatomic, copy) NSString * _Nullable lon;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable os;
@property (nonatomic, copy) NSString * _Nullable agent;
@property (nonatomic, copy) NSString * _Nullable sourceApp;
@property (nonatomic, strong) ICVCustomer * _Nullable customer;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK10ICVScanner")
@interface ICVScanner : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable activeTime;
@property (nonatomic, copy) NSString * _Nullable activePhone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK16ICVStampBusiness")
@interface ICVStampBusiness : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable website;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable district;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK19ICVStampDescription")
@interface ICVStampDescription : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVWidget;

SWIFT_CLASS("_TtC16ICheckViettelSDK14ICVStampDetail")
@interface ICVStampDetail : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable errorMessage;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic) BOOL forceUpdate;
@property (nonatomic) BOOL canUpdate;
@property (nonatomic) BOOL onlyIdentity;
@property (nonatomic, copy) NSString * _Nullable qrm;
@property (nonatomic, strong) ICVScanner * _Nullable currentScanner;
@property (nonatomic, copy) NSArray<ICVWidget *> * _Nonnull widgets;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVStampHotline;

SWIFT_CLASS("_TtC16ICheckViettelSDK13ICVStampError")
@interface ICVStampError : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICVStampHotline * _Nullable hotline;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK17ICVStampGuarantee")
@interface ICVStampGuarantee : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable activeDate;
@property (nonatomic, copy) NSString * _Nullable expireDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK15ICVStampHotline")
@interface ICVStampHotline : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable attachments;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable username;
@property (nonatomic, copy) NSString * _Nullable website;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK13ICVStampInfor")
@interface ICVStampInfor : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable ensign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK15ICVStampMessage")
@interface ICVStampMessage : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable text;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK14ICVStampResult")
@interface ICVStampResult : ICVBaseModel
@property (nonatomic, strong) ICVActive * _Nullable active;
@property (nonatomic, strong) ICVBusiness * _Nullable business;
@property (nonatomic, strong) ICVCount * _Nullable countInfo;
@property (nonatomic, strong) ICVGuarantee * _Nullable guarantee;
@property (nonatomic, strong) ICVProduct * _Nullable product;
@property (nonatomic) BOOL forceUpdate;
@property (nonatomic) BOOL canUpdate;
@property (nonatomic, strong) ICVStampError * _Nullable error;
@property (nonatomic, strong) ICVScanMessage * _Nullable scanMessage;
@property (nonatomic, strong) ICVCurrentScanner * _Nullable currentScanner;
@property (nonatomic) NSInteger showAnalytic;
@property (nonatomic, copy) NSString * _Nullable requirError;
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSArray<ICVEcommerce *> * _Nonnull ecommerces;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK16ICVStampScanInfo")
@interface ICVStampScanInfo : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic) NSInteger scanCount;
@property (nonatomic) NSInteger peopleCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK14ICVStampSerial")
@interface ICVStampSerial : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable serial;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK8ICVStore")
@interface ICVStore : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable deletedTime;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK7ICVTime")
@interface ICVTime : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable active;
@property (nonatomic, copy) NSString * _Nullable expiredDate;
@property (nonatomic, copy) NSString * _Nullable dayRemainingString;
@property (nonatomic, readonly, copy) NSString * _Nonnull unit;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK10ICVVariant")
@interface ICVVariant : ICVBaseModel
@property (nonatomic, copy) NSArray<ICVProductVariant *> * _Nonnull products;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK9ICVVendor")
@interface ICVVendor : ICVBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable glnCode;
@property (nonatomic, copy) NSString * _Nullable info;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable userCreated;
@property (nonatomic, copy) NSString * _Nullable website;
@property (nonatomic, copy) NSString * _Nullable countryName;
@property (nonatomic, copy) NSString * _Nullable countryLogo;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSString * _Nullable wardName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16ICheckViettelSDK9ICVWidget")
@interface ICVWidget : ICVBaseModel
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
