//
//  AppListPresenter.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation
import Hestia

class AppListPresenter: AppListPresenterProtocol {

    weak private var view: AppListViewProtocol?

    init(view: AppListViewProtocol) {
        self.view = view
    }
    
    
}
