//
//  AppListViewController.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit
import Hestia
import Janus
import MiniAppDemoConnectorSDK

class AppListViewController: UIViewController {
    
    // MARK: - variables
    var presenter: AppListPresenterProtocol?
    
    // MARK: - outlets
    @IBOutlet weak var containerView: UIView!

    // MARK: - actions
    
    // MARK: - life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: true)

        let appList = MiniAppList(collectionViewLayout: UICollectionViewFlowLayout())
        appList.appName = terraApp.identity
        appList.delegate = self
        displayViewController(appList, in: self.containerView)
    }
    
    // MARK: - setup
    func displayViewController(_ childVC: UIViewController, in view: UIView) {
        addChild(childVC)
        childVC.view.frame = view.bounds
        view.addSubview(childVC.view)
        childVC.didMove(toParent: self)
    }
    func removeViewController(_ childVC: UIViewController) {
        childVC.willMove(toParent: nil)
        childVC.view.removeFromSuperview()
        childVC.removeFromParent()
    }
    
}

// MARK: - ViewProtocol
extension AppListViewController: AppListViewProtocol {
    
    func showAlert(message: String?) {
        self.showAlertController(message: message)
    }

    
}

extension AppListViewController: MiniAppListDelegate {
    
    func didSelectApp(appList: MiniAppList, appCode: String) {
        guard let hestia = TerraHestia.getInstance(by: terraApp) else {
            print("Has no intances of Hestia competitive with \(terraApp.identity)")
            return
        }
        
        hestia.startApp(onViewController: self, appCode: appCode, delegate: nil, onSuccess: {
            print("Open app successfully")
        }) { error in
            self.showAlert(message: error.rawValue)
        }
    }
    
    
}
