//
//  AppListViewController.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit
import Hestia
import Janus
import JanusUI
import MAPaymentKit
import SVProgressHUD

class AppListViewController: UIViewController {
    
    // MARK: - variables
    var presenter: AppListPresenterProtocol?
    
    // MARK: - outlets
    @IBOutlet weak var containerView: UIView!

    // MARK: - actions
    
    // MARK: - life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(false, animated: true)

        SVProgressHUD.show()
        TerraManager.shared.loadTerra { isSuccess in
            SVProgressHUD.dismiss()
            let appList = MiniAppList(collectionViewLayout: UICollectionViewFlowLayout())
            appList.terraAppName = terraApp.identity
            appList.delegate = self.presenter as? MiniAppListDelegate
            self.displayViewController(appList, in: self.containerView)
        }
        
    }
    
    // MARK: - setup
    func displayViewController(_ childVC: UIViewController, in view: UIView) {
        addChild(childVC)
        childVC.view.frame = view.bounds
        view.addSubview(childVC.view)
        childVC.didMove(toParent: self)
    }
    
    func removeViewController(_ childVC: UIViewController) {
        childVC.willMove(toParent: nil)
        childVC.view.removeFromSuperview()
        childVC.removeFromParent()
    }
    
}

// MARK: - ViewProtocol
extension AppListViewController: AppListViewProtocol {
    func showAlert(message: String?) {
        print("AppListViewProtocol-showAlert \(String(describing: message))")
        showAlertController(message: message)
    }
    
    func openApp(_ app: HestiaApp) {
        guard let hestia = terraHestia else {
            print("Has no intances of Hestia competitive with \(terraApp.identity)")
            return
        }
        print(app.code)
        hestia.startApp(onViewController: self, appCode: app.productCode, appType: app.type, extraConfig: ["bundleId" : Bundle.main.bundleIdentifier ?? ""], callback: presenter as? HestiaCallback)
    }
    
    func openLogin() {
        terraAuthUI?.startLogin(self, delegate: presenter as! LoginUIDelegate, dismissable: true)
    }

}
