//
//  AppListViewController.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit
import Hestia
import Janus
import MiniAppDemoConnectorSDK
import MAPaymentKit
import SVProgressHUD
import TripiFlightKit

class AppListViewController: UIViewController, TripiFlightKitDelegate {
    func didBookOrderWith(jsonData: Data?) {
            
    }
    
    func didBackFromSDK() {
        
    }
    
    
    // MARK: - variables
    var presenter: AppListPresenterProtocol?
    
    // MARK: - outlets
    @IBOutlet weak var containerView: UIView!

    // MARK: - actions
    @IBAction func flightButtonWasTapped(_ sender: Any) {
        openMiniApp(code: "dinogo_flight")
    }
    
    @IBAction func hotelButtonWasTapped(_ sender: Any) {
        openMiniApp(code: "dinogo_hotel")
    }
    
    private func openMiniApp(code: String) {
        ICLoader.startLoading(fromView: self.view)
        
        TerraHestia.getInstance(by: terraApp)?.startApp(onViewController: self, appCode: code, delegate: self, onSuccess: {
            ICLoader.stopLoading()

            print("success")
        }, onFailure: { error in
            ICLoader.stopLoading()

            print(error)
        })
        

    }
    
    // MARK: - life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: true)

        let appList = MiniAppList(collectionViewLayout: UICollectionViewFlowLayout())
        appList.terraAppName = terraApp.identity
        appList.delegate = self
        displayViewController(appList, in: self.containerView)
        
    }
    
    // MARK: - setup
    func displayViewController(_ childVC: UIViewController, in view: UIView) {
        addChild(childVC)
        childVC.view.frame = view.bounds
        view.addSubview(childVC.view)
        childVC.didMove(toParent: self)
    }
    func removeViewController(_ childVC: UIViewController) {
        childVC.willMove(toParent: nil)
        childVC.view.removeFromSuperview()
        childVC.removeFromParent()
    }
    
}

// MARK: - ViewProtocol
extension AppListViewController: AppListViewProtocol {
    
    func showAlert(message: String?) {
        self.showAlertController(message: message)
    }

    
}

extension AppListViewController: MiniAppListDelegate {
    
    func didSelectApp(appList: MiniAppList, appCode: String) {
        guard let hestia = TerraHestia.getInstance(by: terraApp) else {
            print("Has no intances of Hestia competitive with \(terraApp.identity)")
            return
        }
        
        hestia.startApp(onViewController: self, appCode: appCode, delegate: nil, onSuccess: {
            print("Open app successfully")
        }) { error in
            self.showAlert(message: error.rawValue)
        }
    }
    
    
}


extension AppListViewController: HestiaDelegate {
    func callback(data: [String : Any]) {
        
    }
    
}
