//
//  LoginProtocols.swift
//  SuperAppDemo
//
//  Created linhvt on 3/2/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol LoginBuilderProtocol: AnyObject {

}

// MARK: - Presenter
protocol LoginPresenterProtocol: AnyObject {

}

// MARK: - View
protocol LoginViewProtocol: AnyObject {
    var presenter: LoginPresenterProtocol? { get }
    
    func showAlert(message: String?)
    func openAppsList()

}

