//
//  LoginModule.swift
//  SuperAppDemo
//
//  Created linhvt on 3/2/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import UIKit

class LoginModule: LoginBuilderProtocol {

    static func build() -> UIViewController {
        let view = LoginViewController(nibName: "LoginViewController", bundle: nil)
        let presenter = LoginPresenter(view: view)
        
        view.presenter = presenter
        
        return view
    }
}
