// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef ICHECKSOCIALSDK_SWIFT_H
#define ICHECKSOCIALSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ICheckCore;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ICheckSocialSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC15ICheckSocialSDK12ICTopupAgent")
@interface ICTopupAgent : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ICTopupOrder")
@interface ICTopupOrder : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ICTopupPayInput")
@interface ICTopupPayInput : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable payType;
@property (nonatomic, copy) NSString * _Nullable phone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICTopupResultCard;
@class NSNumber;

SWIFT_CLASS("_TtC15ICheckSocialSDK16ICTopupPayResult")
@interface ICTopupPayResult : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable provider;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable transId;
@property (nonatomic, copy) NSString * _Nullable denomination;
@property (nonatomic, strong) ICTopupResultCard * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic) BOOL isUsed;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK17ICTopupResultCard")
@interface ICTopupResultCard : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic, copy) NSString * _Nullable pin;
@property (nonatomic, copy) NSString * _Nullable exprireDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISCity;
@class ISDistrict;
@class ISWard;
@class ISRank;
@class ISInfoPrivacy;
@class ISUserPrivacy;

SWIFT_CLASS("_TtC15ICheckSocialSDK9ISAccount")
@interface ISAccount : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable birthDay;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) ISCity * _Nullable city;
@property (nonatomic, strong) ISDistrict * _Nullable district;
@property (nonatomic, strong) ISWard * _Nullable ward;
@property (nonatomic, copy) NSString * _Nullable background;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, strong) ISRank * _Nullable rank;
@property (nonatomic, copy) NSString * _Nullable linkedFbId;
@property (nonatomic, strong) ISInfoPrivacy * _Nullable infoPrivacy;
@property (nonatomic, strong) ISUserPrivacy * _Nullable userPrivacy;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// NSCoding required initializer.
/// Fills the data from the passed decoder
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required method.
/// Encodes mode properties into the decoder
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISActionData")
@interface ISActionData : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable qrBarcode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISAddress")
@interface ISAddress : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable fax;
@property (nonatomic, copy) NSString * _Nullable address1;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, strong) ISCity * _Nullable city;
@property (nonatomic, strong) ISDistrict * _Nullable district;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, strong) ISWard * _Nullable ward;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// NSCoding required initializer.
/// Fills the data from the passed decoder
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required method.
/// Encodes mode properties into the decoder
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISAppButton")
@interface ISAppButton : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic, copy) NSString * _Nullable labelColor;
@property (nonatomic, copy) NSString * _Nullable scheme;
@property (nonatomic, copy) NSString * _Nullable source;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class ISAppIconColor;

SWIFT_CLASS("_TtC15ICheckSocialSDK16ISAppButtonStyle")
@interface ISAppButtonStyle : ICBaseModel
@property (nonatomic, strong) ISAppIconColor * _Nullable color;
@property (nonatomic, strong) ISAppButton * _Nullable floatButton;
@property (nonatomic, copy) NSArray<ISAppButton *> * _Nullable primaryFunctions;
@property (nonatomic, copy) NSArray<ISAppButton *> * _Nullable secondaryFunctions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISAppIconColor")
@interface ISAppIconColor : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable backgroundColor;
@property (nonatomic, copy) NSString * _Nullable buttonBackgroundColor;
@property (nonatomic, copy) NSString * _Nullable buttonTextColor;
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable iconColor;
@property (nonatomic, copy) NSString * _Nullable iconColorSecondary;
@property (nonatomic, copy) NSString * _Nullable inputBorder;
@property (nonatomic, copy) NSString * _Nullable primary;
@property (nonatomic, copy) NSString * _Nullable primaryDark;
@property (nonatomic, copy) NSString * _Nullable secondary;
@property (nonatomic, copy) NSString * _Nullable secondaryLight;
@property (nonatomic, copy) NSString * _Nullable textHolder;
@property (nonatomic, copy) NSString * _Nullable textPrimary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISAppIconGroup")
@interface ISAppIconGroup : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSArray<ISAppButton *> * _Nullable secondaryFunctions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISAppTheme")
@interface ISAppTheme : ICBaseModel
/// Image
@property (nonatomic, copy) NSString * _Nullable homeHeaderImage;
@property (nonatomic, copy) NSString * _Nullable homeBackgroundImage;
@property (nonatomic, copy) NSString * _Nullable productOverlayImage;
/// Icons
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull bottomBarSelectedIcons;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull bottomBarNormalIcons;
/// Color
@property (nonatomic, strong) UIColor * _Nullable homeHeaderIconColor;
@property (nonatomic, strong) UIColor * _Nullable bottomBarSelectedTextColor;
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIColor * _Nullable normalTextColor;
@property (nonatomic, strong) UIColor * _Nullable secondTextColor;
@property (nonatomic, strong) UIColor * _Nullable disableTextColor;
@property (nonatomic, strong) UIColor * _Nullable lineColor;
@property (nonatomic, strong) UIColor * _Nullable appBackgroundColor;
@property (nonatomic, strong) UIColor * _Nullable popupBackgroundColor;
/// Time
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISAppVersion")
@interface ISAppVersion : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable platform;
@property (nonatomic) BOOL isForced;
@property (nonatomic) BOOL isSuggested;
@property (nonatomic, copy) NSString * _Nullable createById;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable latestDescription;
@property (nonatomic, copy) NSString * _Nullable latestCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISBalance")
@interface ISBalance : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable walletId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISMedia;

SWIFT_CLASS("_TtC15ICheckSocialSDK8ISBanner")
@interface ISBanner : ICBaseModel
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISUser;

SWIFT_CLASS("_TtC15ICheckSocialSDK7ISBrand")
@interface ISBrand : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable objectType;
@property (nonatomic, copy) NSArray<ISUser *> * _Nullable followers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISLocation;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISBusiness")
@interface ISBusiness : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable cover;
@property (nonatomic, strong) ISLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable fax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISButtonPage")
@interface ISButtonPage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISCampaign")
@interface ISCampaign : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISCampaignGift")
@interface ISCampaignGift : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable businessName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISCardType")
@interface ISCardType : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable pin;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic, copy) NSString * _Nullable exprireDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISCarrier")
@interface ISCarrier : ICBaseModel
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSArray<ISCardType *> * _Nonnull cards;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISItemOrder;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISCartItem")
@interface ISCartItem : ICBaseModel
@property (nonatomic, strong) ISBusiness * _Nullable shop;
@property (nonatomic, copy) NSArray<ISItemOrder *> * _Nullable itemOrders;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISCategory")
@interface ISCategory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) NSInteger level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISCategoryAttributeOption;

SWIFT_CLASS("_TtC15ICheckSocialSDK19ISCategoryAttribute")
@interface ISCategoryAttribute : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSArray<ISCategoryAttributeOption *> * _Nullable options;
@property (nonatomic) id _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK25ISCategoryAttributeOption")
@interface ISCategoryAttributeOption : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK16ISCategoryDetail")
@interface ISCategoryDetail : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic) NSInteger level;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSArray<ISCategory *> * _Nullable categoryDescendant;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISProduct;

SWIFT_CLASS("_TtC15ICheckSocialSDK14ISCategoryPage")
@interface ISCategoryPage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSArray<ISProduct *> * _Nullable products;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISCertificate")
@interface ISCertificate : ICBaseModel
@property (nonatomic, strong) ISMedia * _Nullable media;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISChatSticker")
@interface ISChatSticker : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISCity")
@interface ISCity : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISCoinExchange")
@interface ISCoinExchange : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISPage;

SWIFT_CLASS("_TtC15ICheckSocialSDK9ISComment")
@interface ISComment : ICBaseModel
@property (nonatomic, strong) ISUser * _Nullable user;
@property (nonatomic, strong) ISPage * _Nullable page;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, copy) NSArray<ISComment *> * _Nullable replies;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISProductInfo;

SWIFT_CLASS("_TtC15ICheckSocialSDK12ISContribute")
@interface ISContribute : ICBaseModel
@property (nonatomic, strong) ISUser * _Nullable user;
@property (nonatomic) NSInteger upVotes;
@property (nonatomic) NSInteger downVotes;
@property (nonatomic) BOOL isMe;
@property (nonatomic, strong) ISProductInfo * _Nullable productInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class Owner;
@class Attribute;

SWIFT_CLASS("_TtC15ICheckSocialSDK19ISContributionModel")
@interface ISContributionModel : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable images;
@property (nonatomic, strong) Owner * _Nullable owner;
@property (nonatomic, copy) NSArray<Attribute *> * _Nullable attributes;
@property (nonatomic, copy) NSString * _Nullable reason;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK18ISContributionVote")
@interface ISContributionVote : ICBaseModel
@property (nonatomic, strong) ISUser * _Nullable user;
@property (nonatomic) NSInteger upVotes;
@property (nonatomic) NSInteger downVotes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISCountry")
@interface ISCountry : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISCriteria")
@interface ISCriteria : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger position;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK16ISCriteriaFilter")
@interface ISCriteriaFilter : ICBaseModel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISDataRps")
@interface ISDataRps : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable expiredDate;
@property (nonatomic, copy) NSString * _Nullable shipTime;
@property (nonatomic, copy) NSString * _Nullable pin;
@property (nonatomic, copy) NSString * _Nullable serial;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK17ISDeliveryCharges")
@interface ISDeliveryCharges : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISDetailTopup")
@interface ISDetailTopup : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable seri;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISDistance")
@interface ISDistance : ICBaseModel
- (NSString * _Nonnull)displayDistance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISDistrict")
@interface ISDistrict : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISDuration")
@interface ISDuration : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable text;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISEcommerce")
@interface ISEcommerce : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable link;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK7ISEvent")
@interface ISEvent : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable businessName;
@property (nonatomic, copy) NSString * _Nullable beginAt;
@property (nonatomic, copy) NSString * _Nullable endedAt;
@property (nonatomic, copy) NSString * _Nullable id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISEventGiftBox")
@interface ISEventGiftBox : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable dynamicImage;
@property (nonatomic, copy) NSString * _Nullable dynamicImageUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISFlashSale")
@interface ISFlashSale : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, copy) NSArray<ISProduct *> * _Nullable products;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISGiftBox")
@interface ISGiftBox : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, copy) NSString * _Nullable businessName;
@property (nonatomic, copy) NSString * _Nullable remainTime;
@property (nonatomic, copy) NSString * _Nullable logo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISReason;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISGiftItem")
@interface ISGiftItem : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable rewardId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable campaignId;
@property (nonatomic, copy) NSString * _Nullable campaignName;
@property (nonatomic, copy) NSString * _Nullable rewardType;
@property (nonatomic, copy) NSString * _Nullable icoinIcon;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, copy) NSString * _Nullable confirmTime;
@property (nonatomic, copy) NSString * _Nullable cancelTime;
@property (nonatomic, copy) NSString * _Nullable businessName;
@property (nonatomic, copy) NSString * _Nullable remainTime;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable receiveAt;
@property (nonatomic, copy) NSString * _Nullable campaignBanner;
@property (nonatomic, copy) NSString * _Nullable landingUrl;
@property (nonatomic, copy) NSString * _Nullable landingCode;
@property (nonatomic, strong) ISDataRps * _Nullable dataRps;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable orderId;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable reasonOther;
@property (nonatomic, copy) NSArray<ISReason *> * _Nullable reason;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISHistoryFilter")
@interface ISHistoryFilter : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISHistoryPoint")
@interface ISHistoryPoint : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISHistoryTopup")
@interface ISHistoryTopup : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable provider;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable transId;
@property (nonatomic, strong) ISCardType * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable denomination;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISICheckProduct")
@interface ISICheckProduct : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISInfoPrivacy")
@interface ISInfoPrivacy : ICBaseModel
@property (nonatomic) BOOL city;
@property (nonatomic) BOOL phone;
@property (nonatomic) BOOL gender;
@property (nonatomic) BOOL email;
@property (nonatomic) BOOL birthday;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class ISProductInCart;

SWIFT_CLASS("_TtC15ICheckSocialSDK11ISItemOrder")
@interface ISItemOrder : ICBaseModel
@property (nonatomic, strong) ISProductInCart * _Nullable product;
@property (nonatomic) BOOL select;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISKYCDocument;

SWIFT_CLASS("_TtC15ICheckSocialSDK5ISKYC")
@interface ISKYC : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSArray<ISKYCDocument *> * _Nullable documents;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISKYCDocument")
@interface ISKYCDocument : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable documentName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable document;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISRequest;
@class ISLayoutParams;

SWIFT_CLASS("_TtC15ICheckSocialSDK8ISLayout")
@interface ISLayout : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, strong) ISRequest * _Nullable request;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable custom;
@property (nonatomic) id _Nullable data;
@property (nonatomic, strong) ISLayoutParams * _Nullable customParams;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable entityIdList;
@property (nonatomic) BOOL isRequested;
- (nonnull instancetype)initWithId:(NSString * _Nullable)id key:(NSString * _Nullable)key data:(id _Nullable)data custom:(NSDictionary<NSString *, id> * _Nullable)custom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISLayoutParams")
@interface ISLayoutParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ISStep;

SWIFT_CLASS("_TtC15ICheckSocialSDK5ISLeg")
@interface ISLeg : ICBaseModel
@property (nonatomic, strong) ISLocation * _Nullable startLocation;
@property (nonatomic, strong) ISLocation * _Nullable endLocation;
@property (nonatomic, copy) NSArray<ISStep *> * _Nullable steps;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISLocation")
@interface ISLocation : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISLoyaltyInfo")
@interface ISLoyaltyInfo : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable campaignCode;
@property (nonatomic, copy) NSString * _Nullable giftCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK7ISMedia")
@interface ISMedia : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISMediaFilter")
@interface ISMediaFilter : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISMetaPost")
@interface ISMetaPost : ICBaseModel
@property (nonatomic, strong) ISUser * _Nullable user;
@property (nonatomic, strong) ISPage * _Nullable page;
@property (nonatomic, strong) ISProduct * _Nullable product;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISMissionApply;

SWIFT_CLASS("_TtC15ICheckSocialSDK9ISMission")
@interface ISMission : ICBaseModel
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull campaignId;
@property (nonatomic, copy) NSString * _Nonnull campaignImage;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable campaign;
@property (nonatomic, copy) NSString * _Nullable event;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic) NSInteger totalEvent;
@property (nonatomic) NSInteger currentEvent;
@property (nonatomic, copy) NSString * _Nullable eventName;
@property (nonatomic, copy) NSString * _Nullable beginAt;
@property (nonatomic, copy) NSString * _Nullable endAt;
@property (nonatomic, copy) NSString * _Nullable finishedAt;
@property (nonatomic) NSInteger state;
@property (nonatomic) NSInteger finishState;
@property (nonatomic) NSInteger boxAmount;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable guide;
@property (nonatomic, copy) NSString * _Nullable buttonName;
@property (nonatomic, copy) NSString * _Nullable buttonTarget;
@property (nonatomic, copy) NSArray<ISMissionApply *> * _Nullable products;
@property (nonatomic, copy) NSArray<ISMissionApply *> * _Nullable shops;
@property (nonatomic, copy) NSArray<ISMissionApply *> * _Nullable companies;
@property (nonatomic, copy) NSArray<ISMissionApply *> * _Nullable categories;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISMissionApply")
@interface ISMissionApply : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable barcode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISMyID")
@interface ISMyID : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable myId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISPost;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISMyReview")
@interface ISMyReview : ICBaseModel
@property (nonatomic, strong) ISPost * _Nullable review;
@property (nonatomic, copy) NSArray<ISCriteria *> * _Nullable criterias;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISShop;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISNearShop")
@interface ISNearShop : ICBaseModel
@property (nonatomic, strong) ISShop * _Nullable shop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISNews")
@interface ISNews : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull pageIds;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISNewsCategory")
@interface ISNewsCategory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable des;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISNewsDetail")
@interface ISNewsDetail : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable introtext;
@property (nonatomic, copy) NSString * _Nullable introtext2;
@property (nonatomic, copy) NSString * _Nullable fulltext;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable ctaLabel;
@property (nonatomic, copy) NSString * _Nullable ctaUrl;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull pageIds;
@property (nonatomic, copy) NSArray<ISPage *> * _Nonnull pages;
@property (nonatomic, strong) ISNewsCategory * _Nullable articleCategory;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
@class ISNotificationTarget;
@class ISNotificationSource;

SWIFT_CLASS("_TtC15ICheckSocialSDK14ISNotification")
@interface ISNotification : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) ISNotificationTarget * _Nullable target;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, copy) NSArray<ISNotificationSource *> * _Nullable sources;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISNotificationSource")
@interface ISNotificationSource : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable entity;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISNotificationTarget")
@interface ISNotificationTarget : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable entity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISOnBoarding")
@interface ISOnBoarding : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable cta;
@property (nonatomic, strong) UIColor * _Nullable btnColor;
@property (nonatomic, copy) NSString * _Nullable btnName;
@property (nonatomic, copy) NSString * _Nullable landing;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable onboardCTAs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK7ISOrder")
@interface ISOrder : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSArray<ISItemOrder *> * _Nullable orderItem;
@property (nonatomic, strong) ISUser * _Nullable customer;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ISAddress * _Nullable shippingAddress;
@property (nonatomic, strong) ISAddress * _Nullable billingAddress;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable errReport;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable cancelledAt;
@property (nonatomic, copy) NSString * _Nullable completedAt;
@property (nonatomic, strong) ISBusiness * _Nullable shop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISOrderGift")
@interface ISOrderGift : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISPage")
@interface ISPage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, strong) ISMedia * _Nullable cover;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, copy) NSArray<ISUser *> * _Nullable followers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISPageAsset")
@interface ISPageAsset : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK17ISPageDescription")
@interface ISPageDescription : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable mail;
@property (nonatomic, copy) NSString * _Nullable website;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) ISLocation * _Nullable location;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISPageOverview;

SWIFT_CLASS("_TtC15ICheckSocialSDK12ISPageDetail")
@interface ISPageDetail : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL unsubscribeNotice;
@property (nonatomic, strong) ISPageOverview * _Nullable overview;
@property (nonatomic, strong) ISPageDescription * _Nullable detail;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISPageOverview")
@interface ISPageOverview : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSArray<ISUser *> * _Nullable followers;
@property (nonatomic, copy) NSArray<ISButtonPage *> * _Nonnull buttonConfigs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISPageRelate")
@interface ISPageRelate : ICBaseModel
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL isVerify;
@property (nonatomic) BOOL isFollow;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable corver;
@property (nonatomic, copy) NSString * _Nonnull pageType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISPageShop")
@interface ISPageShop : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISPopupAds")
@interface ISPopupAds : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable path;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, copy) NSString * _Nullable document;
@property (nonatomic, copy) NSString * _Nullable deeplink;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable displayType;
@property (nonatomic, copy) NSString * _Nullable deeplinkParams;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISPrivacy;

SWIFT_CLASS("_TtC15ICheckSocialSDK6ISPost")
@interface ISPost : ICBaseModel
@property (nonatomic, strong) ISUser * _Nullable user;
@property (nonatomic, strong) ISPage * _Nullable page;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, strong) ISMetaPost * _Nullable meta;
@property (nonatomic, copy) NSArray<ISComment *> * _Nullable comments;
@property (nonatomic) BOOL disableNotify;
@property (nonatomic, copy) NSArray<ISPrivacy *> * _Nonnull privacy;
@property (nonatomic) BOOL pinned;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSArray<ISCriteria *> * _Nullable criteriaValues;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISPrivacy")
@interface ISPrivacy : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable privacyName;
@property (nonatomic, copy) NSString * _Nullable elementName;
@property (nonatomic, copy) NSString * _Nullable elementCode;
@property (nonatomic, copy) NSString * _Nullable elementDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISPrivacyUser")
@interface ISPrivacyUser : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable privacyElementCode;
@property (nonatomic, copy) NSString * _Nullable privacyCode;
@property (nonatomic, copy) NSString * _Nullable privacyName;
@property (nonatomic, copy) NSString * _Nullable privacyElementName;
@property (nonatomic) NSInteger privacyId;
@property (nonatomic) BOOL selected;
@property (nonatomic, copy) NSString * _Nullable privacyType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISThumbnail;

SWIFT_CLASS("_TtC15ICheckSocialSDK9ISProduct")
@interface ISProduct : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, strong) ISBusiness * _Nullable owner;
@property (nonatomic, strong) ISThumbnail * _Nullable thumbnails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK17ISProductBusiness")
@interface ISProductBusiness : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable tax;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable website;
@property (nonatomic, copy) NSString * _Nullable facebook;
@property (nonatomic, copy) NSString * _Nullable youtube;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK19ISProductCollection")
@interface ISProductCollection : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable bannerId;
@property (nonatomic, copy) NSString * _Nullable bannerUrl;
@property (nonatomic, copy) NSString * _Nullable bannerSize;
@property (nonatomic, copy) NSString * _Nullable destinationUrl;
@property (nonatomic, copy) NSString * _Nullable publishedAt;
@property (nonatomic, copy) NSArray<ISProduct *> * _Nullable products;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK21ISProductContribution")
@interface ISProductContribution : ICBaseModel
@property (nonatomic) BOOL isMe;
@property (nonatomic, strong) ISContribute * _Nullable contribution;
@property (nonatomic) BOOL iHasContribution;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISProductDescription")
@interface ISProductDescription : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable shortContent;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISProductWarning;

SWIFT_CLASS("_TtC15ICheckSocialSDK15ISProductDetail")
@interface ISProductDetail : ICBaseModel
@property (nonatomic, strong) ISProductInfo * _Nullable info;
@property (nonatomic, strong) ISProductContribution * _Nullable contribution;
@property (nonatomic, copy) NSArray<ISProductBusiness *> * _Nullable distributors;
@property (nonatomic, copy) NSArray<ISProductDescription *> * _Nullable information;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic, strong) ISProductBusiness * _Nullable owner;
@property (nonatomic, strong) ISProductBusiness * _Nullable vendor;
@property (nonatomic, copy) NSArray<ISCriteria *> * _Nullable criterias;
@property (nonatomic, strong) ISProductBusiness * _Nullable manager;
@property (nonatomic, strong) ISProductWarning * _Nullable warning;
@property (nonatomic, strong) ISLoyaltyInfo * _Nullable loyaltyInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISProductInCart")
@interface ISProductInCart : ICBaseModel
@property (nonatomic) id _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK16ISProductInStore")
@interface ISProductInStore : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable cateStr;
@property (nonatomic, copy) NSString * _Nullable image;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISProductInfo")
@interface ISProductInfo : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable barcode;
@property (nonatomic, strong) ISCountry * _Nullable country;
@property (nonatomic, copy) NSArray<ISMedia *> * _Nullable media;
@property (nonatomic) BOOL iHasContribution;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISProductInformation")
@interface ISProductInformation : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISProductOrderFilter")
@interface ISProductOrderFilter : ICBaseModel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK21ISProductVerification")
@interface ISProductVerification : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable verifyMessage;
@property (nonatomic, copy) NSString * _Nullable supportUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK16ISProductWarning")
@interface ISProductWarning : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable images;
@property (nonatomic, copy) NSString * _Nullable level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISPurchase")
@interface ISPurchase : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSArray<ISItemOrder *> * _Nullable products;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISRank")
@interface ISRank : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable expiredDate;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISRanking")
@interface ISRanking : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable expiredDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK8ISReason")
@interface ISReason : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK10ISReminder")
@interface ISReminder : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable redirectPath;
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, copy) NSString * _Nullable entityType;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable actionLabel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISReportReason")
@interface ISReportReason : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable reportType;
@property (nonatomic, copy) NSString * _Nullable des;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISReportResult")
@interface ISReportResult : ICBaseModel
@property (nonatomic, copy) NSArray<ISReportReason *> * _Nullable reports;
@property (nonatomic, copy) NSString * _Nullable message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISRequest")
@interface ISRequest : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class ISResponseValidation;

SWIFT_CLASS("_TtC15ICheckSocialSDK10ISResponse")
@interface ISResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable statusCode;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable messages;
@property (nonatomic, copy) NSArray<ISLayout *> * _Nullable layouts;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic) id _Nullable unknownData;
@property (nonatomic, copy) NSArray<ISResponseValidation *> * _Nullable validationErrors;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@property (nonatomic, readonly, copy) NSString * _Nullable messageWithError;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK20ISResponseValidation")
@interface ISResponseValidation : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable property;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable constraints;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK7ISRoute")
@interface ISRoute : ICBaseModel
@property (nonatomic, strong) ISDistance * _Nullable distance;
@property (nonatomic, strong) ISDuration * _Nullable duration;
@property (nonatomic, copy) NSArray<ISLocation *> * _Nullable snappedWaypoints;
@property (nonatomic, copy) NSArray<ISLeg *> * _Nullable legs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISScanHistory")
@interface ISScanHistory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable actionType;
@property (nonatomic, strong) ISNearShop * _Nullable nearestShop;
@property (nonatomic, strong) ISProductInStore * _Nullable product;
@property (nonatomic, strong) ISActionData * _Nullable actionData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISSearchKeyword")
@interface ISSearchKeyword : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISSession")
@interface ISSession : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable firebaseToken;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, strong) ISAccount * _Nullable user;
@property (nonatomic) BOOL firstLogin;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ISSession (SWIFT_EXTENSION(ICheckSocialSDK))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ISSession * _Nullable current;)
+ (ISSession * _Nullable)current SWIFT_WARN_UNUSED_RESULT;
+ (void)setCurrent:(ISSession * _Nullable)newValue;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK9ISSetting")
@interface ISSetting : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISShop")
@interface ISShop : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable cover;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic) BOOL verified;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ISLocation * _Nullable location;
@property (nonatomic, strong) ISLocation * _Nullable newLocation;
@property (nonatomic) BOOL isOffline;
@property (nonatomic) BOOL isOnline;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) ISCountry * _Nullable country;
@property (nonatomic, strong) ISCity * _Nullable city;
@property (nonatomic, strong) ISDistrict * _Nullable district;
@property (nonatomic, strong) ISWard * _Nullable ward;
@property (nonatomic, copy) NSString * _Nullable fax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISStep")
@interface ISStep : ICBaseModel
@property (nonatomic, strong) ISLocation * _Nullable startLocation;
@property (nonatomic, strong) ISLocation * _Nullable endLocation;
@property (nonatomic, strong) ISDistance * _Nullable distance;
@property (nonatomic, strong) ISDistance * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable streetName;
@property (nonatomic, copy) NSString * _Nullable polyline;
@property (nonatomic, copy) NSArray<ISLocation *> * _Nullable locations;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISSuggestWords")
@interface ISSuggestWords : ICBaseModel
@property (nonatomic) NSInteger count;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull items;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISSummaryReview")
@interface ISSummaryReview : ICBaseModel
@property (nonatomic, copy) NSArray<ISCriteria *> * _Nullable criterias;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISSystemSetting")
@interface ISSystemSetting : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger order;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable regex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISTerraToken")
@interface ISTerraToken : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable token;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK11ISThumbnail")
@interface ISThumbnail : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable medium;
@property (nonatomic, copy) NSString * _Nullable original;
@property (nonatomic, copy) NSString * _Nullable small;
@property (nonatomic, copy) NSString * _Nullable square;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK7ISTopic")
@interface ISTopic : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable avatar;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ISTopupValue;

SWIFT_CLASS("_TtC15ICheckSocialSDK7ISTopup")
@interface ISTopup : ICBaseModel
@property (nonatomic, copy) NSArray<ISTopupValue *> * _Nonnull cards;
@property (nonatomic, copy) NSArray<ISTopupValue *> * _Nonnull mobiles;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK16ISTopupPayMethod")
@interface ISTopupPayMethod : ICBaseModel
@property (nonatomic, strong) ICTopupAgent * _Nullable agent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK12ISTopupValue")
@interface ISTopupValue : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable provider;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull denomination;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK14ISTransparency")
@interface ISTransparency : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISUser")
@interface ISUser : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, strong) ISCity * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ISRank * _Nullable rank;
@property (nonatomic, strong) ISInfoPrivacy * _Nullable infoPrivacy;
@property (nonatomic, strong) ISUserPrivacy * _Nullable userPrivacy;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK15ISUserHasReward")
@interface ISUserHasReward : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable businessName;
@property (nonatomic, copy) NSString * _Nullable icoinIcon;
@property (nonatomic, copy) NSString * _Nullable rewardName;
@property (nonatomic, copy) NSString * _Nullable rewardImage;
@property (nonatomic, copy) NSString * _Nullable receiveAt;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable userId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK18ISUserNoFollowPage")
@interface ISUserNoFollowPage : ICBaseModel
@property (nonatomic) NSInteger count;
@property (nonatomic, copy) NSArray<ISUser *> * _Nonnull rows;
@property (nonatomic) NSInteger maxInvitationCount;
@property (nonatomic) NSInteger invitationCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK13ISUserPrivacy")
@interface ISUserPrivacy : ICBaseModel
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15ICheckSocialSDK6ISWard")
@interface ISWard : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
