//
//  AppListProtocols.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation
import Hestia

// MARK: - Builder
protocol AppListBuilderProtocol: AnyObject {

}

// MARK: - Presenter
protocol AppListPresenterProtocol: AnyObject {
    
}

// MARK: - View
protocol AppListViewProtocol: AnyObject {
    var presenter: AppListPresenterProtocol? { get }
    
    func showAlert(message: String?)
    func openLogin()
    func openApp(_ app: HestiaApp)
}

