//
//  AppListProtocols.swift
//  Hestia
//
//  Created linhvt on 11/16/20.
//  Copyright © 2020 Tung Nguyen. All rights reserved.
//
//  Template generated by LinhVT - @linh.deli
//

import Foundation

// MARK: - Builder
protocol AppListBuilderProtocol: class {

}

// MARK: - Presenter
protocol AppListPresenterProtocol: class {
    
}

// MARK: - View
protocol AppListViewProtocol: class {
    var presenter: AppListPresenterProtocol? { get }
    
    func showAlert(message: String?)
    
}

