#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef LOYALTYSDK_SWIFT_H
#define LOYALTYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ICheckCore;
@import ICheckNetworking;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LoyaltySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC10LoyaltySDK11ICGameAgent")
@interface ICGameAgent : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICLoyBoxGift")
@interface ICLoyBoxGift : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelImage;
@class ICLoyOwner;
@class ICLuckyWheelBox;
@class ICLoyWinnerPoint;
@class ICLoyGameUser;

SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyCampaign")
@interface ICLoyCampaign : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, copy) NSString * _Nullable des;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, copy) NSString * _Nullable publishType;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable startAt;
@property (nonatomic, copy) NSString * _Nullable endAt;
@property (nonatomic, copy) NSString * _Nullable publishAt;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable titleButton;
@property (nonatomic, copy) NSString * _Nullable landingPage;
@property (nonatomic, copy) NSString * _Nullable schemaButton;
@property (nonatomic, strong) ICLuckyWheelBox * _Nullable box;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable headerImage;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable backgroundImage;
@property (nonatomic, copy) NSArray<ICLoyWinnerPoint *> * _Nullable winnerPoints;
@property (nonatomic, copy) NSArray<ICLoyGameUser *> * _Nullable gameUsers;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable introductionImage;
@property (nonatomic, copy) NSString * _Nullable targetValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyCode")
@interface ICLoyCode : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyCustomer")
@interface ICLoyCustomer : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable note;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyGame")
@interface ICLoyGame : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK21ICLoyGamePlayResponse")
@interface ICLoyGamePlayResponse : ICBaseModel
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyGameUser")
@interface ICLoyGameUser : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLoyaltyVoucher;

SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyGift")
@interface ICLoyGift : ICBaseModel
@property (nonatomic, strong) id _Nullable campaignCount;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, strong) id _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, copy) NSString * _Nullable sponsorType;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable shop_image;
@property (nonatomic, copy) NSString * _Nullable shop_name;
@property (nonatomic, strong) ICLoyaltyVoucher * _Nullable voucher;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLoyWinner;

SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyGiftResponse")
@interface ICLoyGiftResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyInstance")
@interface ICLoyInstance : ICBaseInstance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ICLoyInstance * _Nonnull shared;)
+ (ICLoyInstance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nullable (^ _Nullable authorizationBlock)(void);
@property (nonatomic, copy) NSString * _Nullable (^ _Nullable deviceBlock)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyNetworkError")
@interface ICLoyNetworkError : ICBaseModel
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable errorDescription;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nullable statusString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK20ICLoyNetworkResponse")
@interface ICLoyNetworkResponse : ICBaseModel
@property (nonatomic) id _Nullable data;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK10ICLoyOwner")
@interface ICLoyOwner : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK14ICLoyPointGift")
@interface ICLoyPointGift : ICBaseModel
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable exportGiftTo;
@property (nonatomic, copy) NSString * _Nullable exportGiftFrom;
@property (nonatomic, strong) ICLoyaltyVoucher * _Nullable voucher;
@property (nonatomic, strong) ICLoyBoxGift * _Nullable boxGift;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyPointHistory")
@interface ICLoyPointHistory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic, copy) NSString * _Nullable giftName;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyPointOperator")
@interface ICLoyPointOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyPointResponse")
@interface ICLoyPointResponse : ICBaseModel
@property (nonatomic) NSInteger point;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyScanQRHistory")
@interface ICLoyScanQRHistory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable target;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICWinnerGift;

SWIFT_CLASS("_TtC10LoyaltySDK11ICLoyWinner")
@interface ICLoyWinner : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable businessOwnerName;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable fullAddress;
@property (nonatomic, strong) id _Nullable geo;
@property (nonatomic, strong) id _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) id _Nullable originalTarget;
@property (nonatomic, strong) id _Nullable packageCodeId;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTime;
@property (nonatomic, copy) NSString * _Nullable statusTimeTitle;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
@property (nonatomic, strong) id _Nullable target;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable wardName;
@property (nonatomic, copy) NSString * _Nullable winAt;
@property (nonatomic, copy) NSArray<ICWinnerGift *> * _Nullable winnerGifts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK16ICLoyWinnerPoint")
@interface ICLoyWinnerPoint : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK19ICLoyWinnerResponse")
@interface ICLoyWinnerResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyaltyOperator")
@interface ICLoyaltyOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVoucherChecker;

SWIFT_CLASS("_TtC10LoyaltySDK16ICLoyaltyVoucher")
@interface ICLoyaltyVoucher : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, strong) ICVoucherChecker * _Nullable checker;
@property (nonatomic, copy) NSString * _Nullable end_at;
@property (nonatomic, copy) NSString * _Nullable released_at;
@property (nonatomic, copy) NSString * _Nullable effective_type;
@property (nonatomic, copy) NSString * _Nullable effective_time;
@property (nonatomic, copy) NSString * _Nullable start_at;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICLuckyWheel")
@interface ICLuckyWheel : ICBaseModel
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelBoxGame;

SWIFT_CLASS("_TtC10LoyaltySDK15ICLuckyWheelBox")
@interface ICLuckyWheelBox : ICBaseModel
@property (nonatomic, copy) NSArray<ICLuckyWheelBoxGame *> * _Nullable boxGames;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK19ICLuckyWheelBoxGame")
@interface ICLuckyWheelBoxGame : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, strong) id _Nullable deletedAt;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, strong) id _Nullable giftLevel;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelTheme;

SWIFT_CLASS("_TtC10LoyaltySDK21ICLuckyWheelCampaign1")
@interface ICLuckyWheelCampaign1 : ICBaseModel
@property (nonatomic, strong) ICLuckyWheelBox * _Nullable box;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable endAt;
@property (nonatomic, copy) NSString * _Nullable exportGiftFrom;
@property (nonatomic, copy) NSString * _Nullable exportGiftTo;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable publishAt;
@property (nonatomic, strong) id _Nullable publishType;
@property (nonatomic, strong) id _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable startAt;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTime;
@property (nonatomic, copy) NSString * _Nullable statusTimeTitle;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, strong) ICLuckyWheelTheme * _Nullable theme;
@property (nonatomic, strong) id _Nullable themeImage;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, strong) id _Nullable userCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLuckyWheelImage")
@interface ICLuckyWheelImage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable medium;
@property (nonatomic, copy) NSString * _Nullable original;
@property (nonatomic, copy) NSString * _Nullable small;
@property (nonatomic, copy) NSString * _Nullable square;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK20ICLuckyWheelOperator")
@interface ICLuckyWheelOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLuckyWheelResult")
@interface ICLuckyWheelResult : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLuckyWheelTheme")
@interface ICLuckyWheelTheme : ICBaseModel
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable cover;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelButton;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelEight;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelSix;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelTen;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK16ICVoucherChecker")
@interface ICVoucherChecker : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICWinnerGift")
@interface ICWinnerGift : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef LOYALTYSDK_SWIFT_H
#define LOYALTYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ICheckCore;
@import ICheckNetworking;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LoyaltySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC10LoyaltySDK11ICGameAgent")
@interface ICGameAgent : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICLoyBoxGift")
@interface ICLoyBoxGift : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelImage;
@class ICLoyOwner;
@class ICLuckyWheelBox;
@class ICLoyWinnerPoint;
@class ICLoyGameUser;

SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyCampaign")
@interface ICLoyCampaign : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, copy) NSString * _Nullable des;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, copy) NSString * _Nullable publishType;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable startAt;
@property (nonatomic, copy) NSString * _Nullable endAt;
@property (nonatomic, copy) NSString * _Nullable publishAt;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable titleButton;
@property (nonatomic, copy) NSString * _Nullable landingPage;
@property (nonatomic, copy) NSString * _Nullable schemaButton;
@property (nonatomic, strong) ICLuckyWheelBox * _Nullable box;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable headerImage;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable backgroundImage;
@property (nonatomic, copy) NSArray<ICLoyWinnerPoint *> * _Nullable winnerPoints;
@property (nonatomic, copy) NSArray<ICLoyGameUser *> * _Nullable gameUsers;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable introductionImage;
@property (nonatomic, copy) NSString * _Nullable targetValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyCode")
@interface ICLoyCode : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyCustomer")
@interface ICLoyCustomer : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable note;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyGame")
@interface ICLoyGame : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK21ICLoyGamePlayResponse")
@interface ICLoyGamePlayResponse : ICBaseModel
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyGameUser")
@interface ICLoyGameUser : ICBaseModel
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLoyaltyVoucher;

SWIFT_CLASS("_TtC10LoyaltySDK9ICLoyGift")
@interface ICLoyGift : ICBaseModel
@property (nonatomic, strong) id _Nullable campaignCount;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, strong) id _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, copy) NSString * _Nullable sponsorType;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable shop_image;
@property (nonatomic, copy) NSString * _Nullable shop_name;
@property (nonatomic, strong) ICLoyaltyVoucher * _Nullable voucher;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLoyWinner;

SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyGiftResponse")
@interface ICLoyGiftResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK13ICLoyInstance")
@interface ICLoyInstance : ICBaseInstance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ICLoyInstance * _Nonnull shared;)
+ (ICLoyInstance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nullable (^ _Nullable authorizationBlock)(void);
@property (nonatomic, copy) NSString * _Nullable (^ _Nullable deviceBlock)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyNetworkError")
@interface ICLoyNetworkError : ICBaseModel
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable errorDescription;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nullable statusString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK20ICLoyNetworkResponse")
@interface ICLoyNetworkResponse : ICBaseModel
@property (nonatomic) id _Nullable data;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic, copy) NSString * _Nullable message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK10ICLoyOwner")
@interface ICLoyOwner : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable address;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK14ICLoyPointGift")
@interface ICLoyPointGift : ICBaseModel
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable exportGiftTo;
@property (nonatomic, copy) NSString * _Nullable exportGiftFrom;
@property (nonatomic, strong) ICLoyaltyVoucher * _Nullable voucher;
@property (nonatomic, strong) ICLoyBoxGift * _Nullable boxGift;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyPointHistory")
@interface ICLoyPointHistory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic, copy) NSString * _Nullable giftName;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyPointOperator")
@interface ICLoyPointOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyPointResponse")
@interface ICLoyPointResponse : ICBaseModel
@property (nonatomic) NSInteger point;
@property (nonatomic, strong) ICLoyOwner * _Nullable owner;
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLoyScanQRHistory")
@interface ICLoyScanQRHistory : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable target;
@property (nonatomic, copy) NSString * _Nullable createdAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICWinnerGift;

SWIFT_CLASS("_TtC10LoyaltySDK11ICLoyWinner")
@interface ICLoyWinner : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable businessOwnerName;
@property (nonatomic, copy) NSString * _Nullable cityName;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable districtName;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable fullAddress;
@property (nonatomic, strong) id _Nullable geo;
@property (nonatomic, strong) id _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) id _Nullable originalTarget;
@property (nonatomic, strong) id _Nullable packageCodeId;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTime;
@property (nonatomic, copy) NSString * _Nullable statusTimeTitle;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
@property (nonatomic, strong) id _Nullable target;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable wardName;
@property (nonatomic, copy) NSString * _Nullable winAt;
@property (nonatomic, copy) NSArray<ICWinnerGift *> * _Nullable winnerGifts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK16ICLoyWinnerPoint")
@interface ICLoyWinnerPoint : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK19ICLoyWinnerResponse")
@interface ICLoyWinnerResponse : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLoyaltyOperator")
@interface ICLoyaltyOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICVoucherChecker;

SWIFT_CLASS("_TtC10LoyaltySDK16ICLoyaltyVoucher")
@interface ICLoyaltyVoucher : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable expiredAt;
@property (nonatomic, strong) ICVoucherChecker * _Nullable checker;
@property (nonatomic, copy) NSString * _Nullable end_at;
@property (nonatomic, copy) NSString * _Nullable released_at;
@property (nonatomic, copy) NSString * _Nullable effective_type;
@property (nonatomic, copy) NSString * _Nullable effective_time;
@property (nonatomic, copy) NSString * _Nullable start_at;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICLuckyWheel")
@interface ICLuckyWheel : ICBaseModel
@property (nonatomic, strong) ICLoyCampaign * _Nullable campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelBoxGame;

SWIFT_CLASS("_TtC10LoyaltySDK15ICLuckyWheelBox")
@interface ICLuckyWheelBox : ICBaseModel
@property (nonatomic, copy) NSArray<ICLuckyWheelBoxGame *> * _Nullable boxGames;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK19ICLuckyWheelBoxGame")
@interface ICLuckyWheelBoxGame : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, strong) id _Nullable deletedAt;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, strong) id _Nullable giftLevel;
@property (nonatomic, copy) NSString * _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ICLuckyWheelTheme;

SWIFT_CLASS("_TtC10LoyaltySDK21ICLuckyWheelCampaign1")
@interface ICLuckyWheelCampaign1 : ICBaseModel
@property (nonatomic, strong) ICLuckyWheelBox * _Nullable box;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable endAt;
@property (nonatomic, copy) NSString * _Nullable exportGiftFrom;
@property (nonatomic, copy) NSString * _Nullable exportGiftTo;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable publishAt;
@property (nonatomic, strong) id _Nullable publishType;
@property (nonatomic, strong) id _Nullable reason;
@property (nonatomic, copy) NSString * _Nullable startAt;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable statusTime;
@property (nonatomic, copy) NSString * _Nullable statusTimeTitle;
@property (nonatomic, copy) NSString * _Nullable statusTitle;
@property (nonatomic, copy) NSString * _Nullable targetType;
@property (nonatomic, strong) ICLuckyWheelTheme * _Nullable theme;
@property (nonatomic, strong) id _Nullable themeImage;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
@property (nonatomic, strong) id _Nullable userCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLuckyWheelImage")
@interface ICLuckyWheelImage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable medium;
@property (nonatomic, copy) NSString * _Nullable original;
@property (nonatomic, copy) NSString * _Nullable small;
@property (nonatomic, copy) NSString * _Nullable square;
@property (nonatomic, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK20ICLuckyWheelOperator")
@interface ICLuckyWheelOperator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK18ICLuckyWheelResult")
@interface ICLuckyWheelResult : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSArray<ICLoyGift *> * _Nullable gifts;
@property (nonatomic, strong) ICLoyWinner * _Nullable winner;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK17ICLuckyWheelTheme")
@interface ICLuckyWheelTheme : ICBaseModel
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable avatar;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable cover;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelButton;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelEight;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelSix;
@property (nonatomic, strong) ICLuckyWheelImage * _Nullable imageGameLuckywheelTen;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK16ICVoucherChecker")
@interface ICVoucherChecker : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10LoyaltySDK12ICWinnerGift")
@interface ICWinnerGift : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable deletedAt;
@property (nonatomic, strong) ICLoyGift * _Nullable gift;
@property (nonatomic, copy) NSString * _Nullable updatedAt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
