// Generated by Apple Swift version 5.4 effective-4.1.50 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
#ifndef ICHECKEVS_SWIFT_H
#define ICHECKEVS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ICheckCore;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ICheckEVS",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC9ICheckEVS11ICEBusiness")
@interface ICEBusiness : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable companyEmail;
@property (nonatomic, copy) NSString * _Nullable companyName;
@property (nonatomic, copy) NSString * _Nullable companyWebsite;
@property (nonatomic, copy) NSString * _Nullable cover;
@property (nonatomic, copy) NSString * _Nullable fullname;
@property (nonatomic, copy) NSString * _Nullable icheckId;
@property (nonatomic, copy) NSString * _Nullable logo;
@property (nonatomic, copy) NSString * _Nullable phone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class ICEOtherStore;

SWIFT_CLASS("_TtC9ICheckEVS15ICECustomerInfo")
@interface ICECustomerInfo : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable district;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) ICEOtherStore * _Nullable otherStore;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class NSNumber;

SWIFT_CLASS("_TtC9ICheckEVS8ICEError")
@interface ICEError : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) NSError * _Nullable error;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS12ICEGuarantee")
@interface ICEGuarantee : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, readonly, copy) NSString * _Nonnull statusString;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class ICEOrder;
@class ICEProduct;
@class ICEStamp;
@class ICEStore;
@class ICEUser;

SWIFT_CLASS("_TtC9ICheckEVS15ICEGuaranteeLog")
@interface ICEGuaranteeLog : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable codeId;
@property (nonatomic, copy) NSString * _Nullable codeSms;
@property (nonatomic, copy) NSString * _Nullable createdAt;
@property (nonatomic, strong) ICECustomerInfo * _Nullable customer;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, strong) ICEOrder * _Nullable order;
@property (nonatomic, copy) NSString * _Nullable os;
@property (nonatomic, strong) ICEProduct * _Nullable product;
@property (nonatomic, copy) NSString * _Nullable qrm;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic, strong) ICEStamp * _Nullable stamp;
@property (nonatomic, strong) ICEStore * _Nullable store;
@property (nonatomic, strong) ICEUser * _Nullable user;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ICheckEVS10ICEHotline")
@interface ICEHotline : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable hotline;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS8ICEImage")
@interface ICEImage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS11ICEInstance")
@interface ICEInstance : NSObject
@property (nonatomic, copy) void (^ _Nullable requiredLoginCallBack)(void (^ _Nonnull)(NSString * _Nullable));
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ICEInstance * _Nonnull shared;)
+ (ICEInstance * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)signInCallback:(void (^ _Nullable)(BOOL))callback;
/// \param callBack callback return The ICheck’s token string
///
- (void)setRequiredSignInCallBack:(void (^ _Nullable)(void (^ _Nonnull)(NSString * _Nullable)))callBack;
- (void)signOut;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ICEService;

SWIFT_CLASS("_TtC9ICheckEVS10ICEMessage")
@interface ICEMessage : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) ICEService * _Nullable service;
@property (nonatomic, copy) NSString * _Nullable type;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS11ICEOperator")
@interface ICEOperator : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ICEOperator * _Nonnull shared;)
+ (ICEOperator * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ICEOperator (SWIFT_EXTENSION(ICheckEVS))
- (void)listStoresOfStamp:(NSString * _Nonnull)stampId onSuccess:(void (^ _Nullable)(NSArray<ICEStore *> * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
- (void)listHotlinesOnSuccess:(void (^ _Nullable)(NSArray<ICEHotline *> * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
@end

@class ICESession;
@class ICEStampResult;

@interface ICEOperator (SWIFT_EXTENSION(ICheckEVS))
- (void)signInWithToken:(NSString * _Nonnull)token onSuccess:(void (^ _Nullable)(ICESession * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
- (void)scanQRM:(NSString * _Nonnull)code icheckId:(NSString * _Nullable)icheckId deviceId:(NSString * _Nullable)deviceId phone:(NSString * _Nullable)phone onSuccess:(void (^ _Nullable)(ICEStampResult * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
- (void)scanQRI:(NSString * _Nonnull)code icheckId:(NSString * _Nullable)icheckId deviceId:(NSString * _Nullable)deviceId phone:(NSString * _Nullable)phone onSuccess:(void (^ _Nullable)(ICEStampResult * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
- (void)scanStampV5:(NSString * _Nonnull)code icheckId:(NSString * _Nullable)icheckId deviceId:(NSString * _Nullable)deviceId phone:(NSString * _Nullable)phone onSuccess:(void (^ _Nullable)(ICEStampResult * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
- (void)updateCustomerInfo:(ICECustomerInfo * _Nonnull)customer id:(NSString * _Nonnull)id deviceId:(NSString * _Nullable)deviceId onSuccess:(void (^ _Nullable)(ICECustomerInfo * _Nonnull))onSuccess onFault:(void (^ _Nullable)(ICEError * _Nonnull))onFault;
@end


SWIFT_CLASS("_TtC9ICheckEVS8ICEOrder")
@interface ICEOrder : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable couponId;
@property (nonatomic, copy) NSString * _Nullable domainCheck;
@property (nonatomic, copy) NSString * _Nullable fields;
@property (nonatomic, copy) NSString * _Nullable linkExcel;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable prefix;
@property (nonatomic, copy) NSString * _Nullable stampService;
@property (nonatomic, copy) NSString * _Nullable taskExcelDone;
@property (nonatomic, copy) NSString * _Nullable transactionId;
@property (nonatomic, copy) NSString * _Nullable unitPrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ICheckEVS13ICEOtherStore")
@interface ICEOtherStore : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable district;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable city;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required initializer.
/// Fills the data from the passed decoder
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required method.
/// Encodes mode properties into the decoder
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS10ICEProduct")
@interface ICEProduct : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable descriptionField;
@property (nonatomic, copy) NSString * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) double price;
@property (nonatomic, copy) NSString * _Nullable serialPrefix;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable userCreated;
@property (nonatomic, copy) NSString * _Nullable vendor;
@property (nonatomic, copy) NSArray<ICEImage *> * _Nullable images;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS11ICEResponse")
@interface ICEResponse : ICBaseModel
@property (nonatomic) id _Nullable data;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic) BOOL error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required initializer.
/// Fills the data from the passed decoder
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// NSCoding required method.
/// Encodes mode properties into the decoder
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS10ICEService")
@interface ICEService : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable messageError;
@property (nonatomic, copy) NSString * _Nullable messageSuccess;
@property (nonatomic, copy) NSString * _Nullable messageWarning;
@property (nonatomic, copy) NSString * _Nullable name;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS10ICESession")
@interface ICESession : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable icheckId;
@property (nonatomic, copy) NSString * _Nullable ownerIcheckId;
@property (nonatomic, copy) NSString * _Nullable token;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS8ICEStamp")
@interface ICEStamp : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) NSInteger activeTime;
@property (nonatomic) NSInteger scanTime;
@property (nonatomic, copy) NSString * _Nullable cityScan;
@property (nonatomic, copy) NSString * _Nullable codeId;
@property (nonatomic, copy) NSString * _Nullable codeSms;
@property (nonatomic, copy) NSString * _Nullable countryScan;
@property (nonatomic) NSInteger createdTime;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic) NSInteger expireTime;
@property (nonatomic, copy) NSString * _Nullable geoLocation;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable qrm;
@property (nonatomic, copy) NSString * _Nullable regionScan;
@property (nonatomic, copy) NSString * _Nullable serial;
@property (nonatomic) NSInteger showBusiness;
@property (nonatomic) NSInteger showVendor;
@property (nonatomic, copy) NSString * _Nullable stampService;
@property (nonatomic, copy) NSString * _Nullable taskId;
@property (nonatomic, strong) ICEGuarantee * _Nullable guarantee;
@property (nonatomic, strong) ICECustomerInfo * _Nullable customer;
@property (nonatomic) NSInteger canUpdateInfo;
@property (nonatomic) NSInteger forceUpdate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS14ICEStampResult")
@interface ICEStampResult : ICBaseModel
@property (nonatomic, strong) ICEBusiness * _Nullable business;
@property (nonatomic, copy) NSArray<ICEMessage *> * _Nullable messages;
@property (nonatomic, strong) ICEProduct * _Nullable product;
@property (nonatomic, copy) NSArray<ICEProduct *> * _Nullable otherProduct;
@property (nonatomic, strong) ICEStamp * _Nullable stamp;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, readonly) BOOL isFake;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS8ICEStore")
@interface ICEStore : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable district;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable province;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC9ICheckEVS7ICEUser")
@interface ICEUser : ICBaseModel
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable fullname;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable username;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
